# Generated by Django 4.1.7 on 2023-03-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busqueda_Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Curso', models.CharField(max_length=30)),
                ('Camada', models.CharField(max_length=80)),
            ],
        ),
    ]
