# Generated by Django 4.1.7 on 2023-03-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_busqueda_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pais', models.CharField(max_length=30)),
                ('fecha_de_nacimiento', models.CharField(max_length=80)),
            ],
        ),
    ]
